services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data_test:/data

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user
      MONGO_INITDB_ROOT_PASSWORD: test_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_test:/data/db

  backend:
    build:
      context: .
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_IP: postgres
      REDIS_IP: redis
      MONGO_IP: mongodb
    depends_on:
      - postgres
      - redis
      - mongodb

volumes:
  postgres_data_test:
  redis_data_test:
  mongodb_data_test: