# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
      - redis
    environment:
      MONGO_LOCAL_CURRENT_DATABASE: schedules
      DEFAULT_SERVER_CLUSTER: mongodb

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_API_BASE_URL=http://192.168.56.106:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
    depends_on:
      - frontend
      - backend
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
  mongodb_data:
  redis_data:
  postgres_data:


